name = "quicktrip-api"
main = "src/index.ts"
compatibility_date = "2024-05-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
  binding = "DB"
  database_name = "quicktrip-db"
  database_id = "e86396ef-49f0-44f7-81d0-6b2cf8db75bd"

[env.production]
name = "quicktrip-api-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "quicktrip-prod"
database_id = "your-prod-database-id"